version: "3"
services:
  web:
    build: .
    environment:
      RAILS_ENV: "docker-test"
    command: "./docker-starter.sh"
    ports:
        - "3001:3000"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nikita
      MYSQL_DATABASE: "mymicroblog_development"
      MYSQL_USER: mymicroblog
      MYSQL_PASSWORD: nikita
